name: Run schema validation
on:
  pull_request:
  workflow_dispatch:

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

# needed for Commit and push OpenAPI changes to work
permissions:
  contents: write

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # needed for Commit and push OpenAPI changes to work
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - uses: actions/setup-node@v4
      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Optic lint base OpenAPI spec ahead of other checks
        run: npm run optic:lint

      - name: Bundle OpenAPI to a new file (remove $refs, flatten)
        run: npm run bundle:openapi

      # This workflow exists so we do not have to locally generate api docs (html)
      # If the api doc for Github Pages has changed, it commits and pushes those changes back to the PR branch
      - name: Generate api docs for Github Pages (html)
        run: npm run generate:api-docs

      - name: Check if OpenAPI docs for Github Pages have changed
        id: check_changes
        run: |
          if git diff --quiet docs/api-docs.html; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push api doc changes for Github Pages
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Generate api docs (html)'
          add: 'docs/api-docs.html'
          push: true
          github_token: ${{ secrets.PAT_TOKEN }}

      - name: Create empty commit to re-run checks
        if: env.changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --allow-empty -m "Re-run checks after OpenAPI update"
          git push origin HEAD:${{ github.head_ref }}

      # Schema validation

      - name: Fetch main branch for Optic
        run: git fetch --depth=1 origin main:main

      - name: Optic diff (OpenAPI diff vs snapshot on main)
        run: npm run optic:diff
